### ISSUE TITLE
run local_app.py LlamaCpp load error

### ISSUE THREAD

**Issue by HardSoft2023** [e-johnstonn/BriefGPT#2]
models/ggml-vic13b-q5_1.bin
llama.cpp: loading model from models/ggml-vic13b-q5_1.bin
error loading model: unknown (magic, version) combination: 67676a74, 00000002; is this really a GGML file?
llama_init_from_file: failed to load model

**Comment by e-johnstonn** [comment]
my guess is there's some issue between the version of llama.cpp and the model you're trying to use. the llama.cpp version I used was 0.1.50 - are you using the same version? 

if so, maybe try other versions of llama.cpp - ```pip install llama-cpp-python===version number``` - try with 0.1.45 maybe

**Comment by HardSoft2023** [comment]
I use 0.1.49. 

Actually， the problem is that the file name I specified is incorrect.
It should be **`models/ggml-vic13b-q5_0.bin`**。
so,I suggest replacing the link address in readme from https://huggingface.co/eachadea/ggml-vicuna-13b-1.1/blob/main/ggml-vic13b-q5_1.bin to https://huggingface.co/eachadea/ggml-vicuna-13b-1.1/blob/main/ggml-old-vic13b-q5_0.bin

**Comment by e-johnstonn** [comment]
sorry i dont quite understand, is it working for you now? are you saying the link in the readme is to the wrong version  of llama

**Comment by HardSoft2023** [comment]
yes ,It works, now.
when I change '`models/ggml-vic13b-q5_1.bin`' --->to '**`models/ggml-vic13b-q5_0.bin`**'

**Comment by HardSoft2023** [comment]
**Let me use pictures to explain my problems clearly.**

1. ### This URL in README Llama SHA256 is OK

![SHA256_good](https://github.com/e-johnstonn/BriefGPT/assets/10841581/a86589a9-1da0-42f2-a115-0d07f1f59e6b)

2. ### But can not load properly
![ggml-vic13b-q5_1 bin_not_load](https://github.com/e-johnstonn/BriefGPT/assets/10841581/198992b0-e2d4-4de3-aa18-f45c145dc3cd)

3. ### Use the new URL works good
![good_load](https://github.com/e-johnstonn/BriefGPT/assets/10841581/114b03d0-59a3-47cf-9d2c-498c2456bace)

all this . I made a PR.

**Comment by krstrid** [comment]
Downgrade to 0.1.48 if you want to use LlamaCpp with gpt4all. Got it to work using HardSofts instructions as well as AndreaKiro's. 

https://github.com/imartinez/privateGPT/issues/220
