### ISSUE TITLE
Inference too slow

### ISSUE THREAD

**Issue by usmanxia** [e-johnstonn/BriefGPT#7]
Hi! 

Thank you for sharing your good. Its really a great help to understand langchain and LLMs. 
I am running the model using NVIDIA V100 32GB ram. The model takes a lot of time to response to the questions. The size pdf document I am loading is around 1.4 MB.

Can you please comment on how to improve the response time?

Regards

**Comment by e-johnstonn** [comment]
Inference is all being done on the CPU with the current configuration. I’m no expert on local LLM’s, so I’m afraid I don’t have much advice on how to speed it up. I’ll look into adding a way for people such as yourself to do inference using their GPUs.

**Comment by usmanxia** [comment]
Ah! Got it, thanx
