### ISSUE TITLE
example in test.env doesn't match if statement

### ISSUE THREAD

**Issue by brookssw** [e-johnstonn/BriefGPT#9]
In test.env, it mentions `MODEL_TYPE = LlamaCpp or GPT4ALL`

However, in local_app.py the if statement is as follows:

`elif model_type == 'GPT4All':`

This causes it to never match, as the L's are uppercase in test.env, but lowercase in the if statement.

I tried to create a branch and submit a PR for this but got 401, though that could be entirely my fault

**Comment by e-johnstonn** [comment]
fixed, thanks!
